import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "storage/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      "src/generated/**",
      // Generated by Next.js on every build; not ours to lint.
      "next-env.d.ts",
    ],
  },
  {
    rules: {
      // Unused variables are an error, but conventional throwaway prefixes are allowed.
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      // `any` defeats the strictness the rest of the codebase relies on.
      "@typescript-eslint/no-explicit-any": "error",
      // Prisma JSON columns require targeted casts; those are annotated at the call site.
      "@typescript-eslint/no-empty-object-type": "warn",
      "react-hooks/exhaustive-deps": "warn",
      /*
       * Images in this application are private employee content served through
       * /api/media/[id], which authorizes the request before streaming a byte.
       * next/image would fetch through its own optimizer loader, bypassing that
       * check, so a plain <img> is the correct choice here rather than a
       * shortcut. Avatars and lesson media are also small and already sized.
       */
      "@next/next/no-img-element": "off",
    },
  },
  {
    // Seed and test files may use looser typing against fixture data.
    files: ["prisma/**/*.ts", "tests/**/*.ts", "e2e/**/*.ts"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
    },
  },
];

export default config;
