/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditChangeLog {
  actor_label: string;
  actor_principal_id: string | null;
  actor_type: string;
  after: Json | null;
  /**
   * Prior column values, with SECRET-classified fields replaced by [redacted] and PII-classified fields subject to erasure (ADR-0027).
   */
  before: Json | null;
  causation_id: string | null;
  changed_fields: string[] | null;
  client_ip: string | null;
  correlation_id: string;
  entity_id: string;
  entity_schema: string;
  entity_table: string;
  id: Generated<string>;
  interface: string;
  occurred_at: Generated<Timestamp>;
  operating_company: string | null;
  /**
   * DENY records an authorization denial (spec §81 criterion 2), which is auditable even though nothing changed.
   */
  operation: string;
  reason: string | null;
  source_record_id: string | null;
  user_agent: string | null;
}

export interface EventsConsumerCursor {
  consumer_key: string;
  last_sequence: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface EventsConsumerInbox {
  consumer_key: string;
  event_id: string;
  processed_at: Generated<Timestamp>;
}

export interface EventsDomainEvent {
  actor_label: string;
  actor_principal_id: string | null;
  actor_type: string;
  aggregate_id: string;
  aggregate_type: string;
  causation_id: string | null;
  correlation_id: string;
  event_type: string;
  id: Generated<string>;
  occurred_at: Timestamp;
  operating_company: string | null;
  payload: Json;
  recorded_at: Generated<Timestamp>;
  schema_version: number;
  /**
   * Total order equal to commit order. Safe to tail: sequence > cursor cannot skip a committed event. See ADR-0008.
   */
  sequence: Int8;
  /**
   * What caused this event: an interface (http), a connector (connector:p21), or a job (job:reconcile). Distinct from the actor, which is who.
   */
  source: string;
}

export interface EventsEventDelivery {
  attempts: Generated<number>;
  claimed_at: Timestamp | null;
  claimed_by: string | null;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  event_id: string;
  id: Generated<string>;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  status: Generated<string>;
  subscription_id: string;
}

export interface EventsEventTypeVersion {
  aggregate_type: string;
  deprecated_at: Timestamp | null;
  description: string;
  event_type: string;
  introduced_at: Generated<Timestamp>;
  json_schema: Json;
  producer_module: string;
  schema_version: number;
}

export interface EventsSubscription {
  created_at: Generated<Timestamp>;
  endpoint_url: string | null;
  event_type_patterns: Generated<string[]>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  key: string;
  kind: string;
  max_attempts: Generated<number>;
  name: string;
  signing_secret_ref: string | null;
}

export interface KernelIdempotencyKey {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  endpoint: string;
  expires_at: Timestamp;
  id: Generated<string>;
  idempotency_key: string;
  principal_id: string;
  request_fingerprint: string;
  response_body: Json | null;
  response_status: number | null;
  state: Generated<string>;
}

export interface KernelOperatingCompany {
  code: string;
  created_at: Generated<Timestamp>;
  is_active: Generated<boolean>;
  /**
   * True only for FSW_GROUP, which is the scope that spans all companies.
   */
  is_group: Generated<boolean>;
  name: string;
}

export interface KernelSchemaMigration {
  applied_at: Generated<Timestamp>;
  applied_by: string;
  execution_ms: number;
  name: string;
  sha256: string;
  version: string;
}

export interface KernelSourceSystem {
  code: string;
  contains_pii: Generated<boolean>;
  created_at: Generated<Timestamp>;
  /**
   * Lower wins. Used only when a field has no explicit survivorship rule.
   */
  default_priority: Generated<number>;
  description: string | null;
  is_active: Generated<boolean>;
  kind: string;
  name: string;
}

export interface DB {
  "audit.change_log": AuditChangeLog;
  "events.consumer_cursor": EventsConsumerCursor;
  "events.consumer_inbox": EventsConsumerInbox;
  "events.domain_event": EventsDomainEvent;
  "events.event_delivery": EventsEventDelivery;
  "events.event_type_version": EventsEventTypeVersion;
  "events.subscription": EventsSubscription;
  "kernel.idempotency_key": KernelIdempotencyKey;
  "kernel.operating_company": KernelOperatingCompany;
  "kernel.schema_migration": KernelSchemaMigration;
  "kernel.source_system": KernelSourceSystem;
}
