/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditChangeLog {
  actor_label: string;
  actor_principal_id: string | null;
  actor_type: string;
  after: Json | null;
  /**
   * Prior column values, with SECRET-classified fields replaced by [redacted] and PII-classified fields subject to erasure (ADR-0027).
   */
  before: Json | null;
  causation_id: string | null;
  changed_fields: string[] | null;
  client_ip: string | null;
  correlation_id: string;
  entity_id: string;
  entity_schema: string;
  entity_table: string;
  id: Generated<string>;
  interface: string;
  occurred_at: Generated<Timestamp>;
  operating_company: string | null;
  /**
   * DENY records an authorization denial (spec §81 criterion 2), which is auditable even though nothing changed.
   */
  operation: string;
  reason: string | null;
  source_record_id: string | null;
  user_agent: string | null;
}

export interface EventsConsumerCursor {
  consumer_key: string;
  last_sequence: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface EventsConsumerInbox {
  consumer_key: string;
  event_id: string;
  processed_at: Generated<Timestamp>;
}

export interface EventsDomainEvent {
  actor_label: string;
  actor_principal_id: string | null;
  actor_type: string;
  aggregate_id: string;
  aggregate_type: string;
  causation_id: string | null;
  correlation_id: string;
  event_type: string;
  id: Generated<string>;
  occurred_at: Timestamp;
  operating_company: string | null;
  payload: Json;
  recorded_at: Generated<Timestamp>;
  schema_version: number;
  /**
   * Total order equal to commit order. Safe to tail: sequence > cursor cannot skip a committed event. See ADR-0008.
   */
  sequence: Int8;
  /**
   * What caused this event: an interface (http), a connector (connector:p21), or a job (job:reconcile). Distinct from the actor, which is who.
   */
  source: string;
}

export interface EventsEventDelivery {
  attempts: Generated<number>;
  claimed_at: Timestamp | null;
  claimed_by: string | null;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  event_id: string;
  id: Generated<string>;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  status: Generated<string>;
  subscription_id: string;
}

export interface EventsEventTypeVersion {
  aggregate_type: string;
  deprecated_at: Timestamp | null;
  description: string;
  event_type: string;
  introduced_at: Generated<Timestamp>;
  json_schema: Json;
  producer_module: string;
  schema_version: number;
}

export interface EventsSubscription {
  created_at: Generated<Timestamp>;
  endpoint_url: string | null;
  event_type_patterns: Generated<string[]>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  key: string;
  kind: string;
  max_attempts: Generated<number>;
  name: string;
  signing_secret_ref: string | null;
}

export interface KernelIdempotencyKey {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  endpoint: string;
  expires_at: Timestamp;
  id: Generated<string>;
  idempotency_key: string;
  principal_id: string;
  request_fingerprint: string;
  response_body: Json | null;
  response_status: number | null;
  state: Generated<string>;
}

export interface KernelOperatingCompany {
  code: string;
  created_at: Generated<Timestamp>;
  is_active: Generated<boolean>;
  /**
   * True only for FSW_GROUP, which is the scope that spans all companies.
   */
  is_group: Generated<boolean>;
  name: string;
}

export interface KernelSchemaMigration {
  applied_at: Generated<Timestamp>;
  applied_by: string;
  execution_ms: number;
  name: string;
  sha256: string;
  version: string;
}

export interface KernelSourceSystem {
  code: string;
  contains_pii: Generated<boolean>;
  created_at: Generated<Timestamp>;
  /**
   * Lower wins. Used only when a field has no explicit survivorship rule.
   */
  default_priority: Generated<number>;
  description: string | null;
  is_active: Generated<boolean>;
  kind: string;
  name: string;
}

export interface PimAttribute {
  cardinality: Generated<string>;
  channels: Generated<string[]>;
  created_at: Generated<Timestamp>;
  default_unit_code: string | null;
  definition_version: Generated<number>;
  deprecated_at: Timestamp | null;
  description: string;
  dimension_code: string | null;
  entity_type: string | null;
  id: Generated<string>;
  is_comparable: Generated<boolean>;
  is_filterable: Generated<boolean>;
  key: string;
  max_length: number | null;
  max_numeric: Numeric | null;
  min_length: number | null;
  min_numeric: Numeric | null;
  name: string;
  numeric_scale: number | null;
  required_designation_kind: Generated<string | null>;
  /**
   * Attributes are deprecated and superseded, never deleted: values already recorded against them remain meaningful.
   */
  superseded_by_key: string | null;
  updated_at: Generated<Timestamp>;
  /**
   * NOMINAL_SIZE and PRESSURE_CLASS are deliberately distinct from ENUM and from QUANTITY. Making them their own value types is what makes it structurally impossible for Class 150 to be stored as, or compared against, 150 PSI (ADR-0016).
   */
  value_type: string;
  vocabulary_key: string | null;
}

export interface PimMetadataVersion {
  applied_at: Generated<Timestamp>;
  applied_by: string;
  content_hash: string;
  file_count: number;
  id: Generated<string>;
  note: string | null;
  summary: Json;
}

export interface PimProductType {
  created_at: Generated<Timestamp>;
  deprecated_at: Timestamp | null;
  description: string;
  etim_class: string | null;
  etim_release: string | null;
  id: Generated<string>;
  key: string;
  name: string;
  parent_key: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PimProductTypeAttribute {
  attribute_key: string;
  /**
   * Applicability predicate in the FSW rule DSL. If actuation is electric, voltage becomes applicable; if pneumatic, supply pressure does. Data, not code.
   */
  condition: Json | null;
  condition_note: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  level: Generated<string>;
  product_type_key: string;
  requirement: Generated<string>;
  sort_order: Generated<number>;
}

export interface PimQuantityDimension {
  code: string;
  description: string;
  name: string;
}

export interface PimUnit {
  code: string;
  dimension_code: string;
  /**
   * Exact where the definition is exact: 1 [in_i] = 25.4 mm by definition.
   */
  factor_to_base: Numeric;
  is_base: Generated<boolean>;
  name: string;
  offset_to_base: Generated<Numeric>;
  sort_order: Generated<number>;
  symbol: string;
}

export interface PimUnitAlias {
  alias: string;
  id: Generated<string>;
  normalized_alias: Generated<string | null>;
  unit_code: string;
}

export interface PimVocabulary {
  created_at: Generated<Timestamp>;
  description: string;
  designation_kind: string | null;
  is_designation: Generated<boolean>;
  key: string;
  name: string;
}

export interface PimVocabularyTerm {
  code: string;
  created_at: Generated<Timestamp>;
  deprecated_at: Timestamp | null;
  description: string | null;
  /**
   * The designation itself: 1, DN25, 150, PN16. For a pressure class the numeral is part of the designation and is NEVER a pressure value.
   */
  designation: string | null;
  id: Generated<string>;
  label: string;
  parent_id: string | null;
  reference_standard: string | null;
  size_system: string | null;
  /**
   * Display and comparison ordering only. Not a measurement and not convertible.
   */
  sort_ordinal: Numeric | null;
  vocabulary_key: string;
}

export interface PimVocabularyTermAlias {
  alias: string;
  asserts_equivalence: Generated<boolean>;
  confidence: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  normalized_alias: Generated<string | null>;
  note: string | null;
  source_system_code: string | null;
  term_id: string;
  vocabulary_key: string;
}

export interface DB {
  "audit.change_log": AuditChangeLog;
  "events.consumer_cursor": EventsConsumerCursor;
  "events.consumer_inbox": EventsConsumerInbox;
  "events.domain_event": EventsDomainEvent;
  "events.event_delivery": EventsEventDelivery;
  "events.event_type_version": EventsEventTypeVersion;
  "events.subscription": EventsSubscription;
  "kernel.idempotency_key": KernelIdempotencyKey;
  "kernel.operating_company": KernelOperatingCompany;
  "kernel.schema_migration": KernelSchemaMigration;
  "kernel.source_system": KernelSourceSystem;
  "pim.attribute": PimAttribute;
  "pim.metadata_version": PimMetadataVersion;
  "pim.product_type": PimProductType;
  "pim.product_type_attribute": PimProductTypeAttribute;
  "pim.quantity_dimension": PimQuantityDimension;
  "pim.unit": PimUnit;
  "pim.unit_alias": PimUnitAlias;
  "pim.vocabulary": PimVocabulary;
  "pim.vocabulary_term": PimVocabularyTerm;
  "pim.vocabulary_term_alias": PimVocabularyTermAlias;
}
