/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditChangeLog {
  actor_label: string;
  actor_principal_id: string | null;
  actor_type: string;
  after: Json | null;
  /**
   * Prior column values, with SECRET-classified fields replaced by [redacted] and PII-classified fields subject to erasure (ADR-0027).
   */
  before: Json | null;
  causation_id: string | null;
  changed_fields: string[] | null;
  client_ip: string | null;
  correlation_id: string;
  entity_id: string;
  entity_schema: string;
  entity_table: string;
  id: Generated<string>;
  interface: string;
  occurred_at: Generated<Timestamp>;
  operating_company: string | null;
  /**
   * DENY records an authorization denial (spec §81 criterion 2), which is auditable even though nothing changed.
   */
  operation: string;
  reason: string | null;
  source_record_id: string | null;
  user_agent: string | null;
}

export interface EventsConsumerCursor {
  consumer_key: string;
  last_sequence: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface EventsConsumerInbox {
  consumer_key: string;
  event_id: string;
  processed_at: Generated<Timestamp>;
}

export interface EventsDomainEvent {
  actor_label: string;
  actor_principal_id: string | null;
  actor_type: string;
  aggregate_id: string;
  aggregate_type: string;
  causation_id: string | null;
  correlation_id: string;
  event_type: string;
  id: Generated<string>;
  occurred_at: Timestamp;
  operating_company: string | null;
  payload: Json;
  recorded_at: Generated<Timestamp>;
  schema_version: number;
  /**
   * Total order equal to commit order. Safe to tail: sequence > cursor cannot skip a committed event. See ADR-0008.
   */
  sequence: Int8;
  /**
   * What caused this event: an interface (http), a connector (connector:p21), or a job (job:reconcile). Distinct from the actor, which is who.
   */
  source: string;
}

export interface EventsEventDelivery {
  attempts: Generated<number>;
  claimed_at: Timestamp | null;
  claimed_by: string | null;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  event_id: string;
  id: Generated<string>;
  last_error: string | null;
  next_attempt_at: Generated<Timestamp>;
  status: Generated<string>;
  subscription_id: string;
}

export interface EventsEventTypeVersion {
  aggregate_type: string;
  deprecated_at: Timestamp | null;
  description: string;
  event_type: string;
  introduced_at: Generated<Timestamp>;
  json_schema: Json;
  producer_module: string;
  schema_version: number;
}

export interface EventsSubscription {
  created_at: Generated<Timestamp>;
  endpoint_url: string | null;
  event_type_patterns: Generated<string[]>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  key: string;
  kind: string;
  max_attempts: Generated<number>;
  name: string;
  signing_secret_ref: string | null;
}

export interface KernelIdempotencyKey {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  endpoint: string;
  expires_at: Timestamp;
  id: Generated<string>;
  idempotency_key: string;
  principal_id: string;
  request_fingerprint: string;
  response_body: Json | null;
  response_status: number | null;
  state: Generated<string>;
}

export interface KernelOperatingCompany {
  code: string;
  created_at: Generated<Timestamp>;
  is_active: Generated<boolean>;
  /**
   * True only for FSW_GROUP, which is the scope that spans all companies.
   */
  is_group: Generated<boolean>;
  name: string;
}

export interface KernelSchemaMigration {
  applied_at: Generated<Timestamp>;
  applied_by: string;
  execution_ms: number;
  name: string;
  sha256: string;
  version: string;
}

export interface KernelSourceSystem {
  code: string;
  contains_pii: Generated<boolean>;
  created_at: Generated<Timestamp>;
  /**
   * Lower wins. Used only when a field has no explicit survivorship rule.
   */
  default_priority: Generated<number>;
  description: string | null;
  is_active: Generated<boolean>;
  kind: string;
  name: string;
}

export interface PimAttribute {
  cardinality: Generated<string>;
  channels: Generated<string[]>;
  created_at: Generated<Timestamp>;
  default_unit_code: string | null;
  definition_version: Generated<number>;
  deprecated_at: Timestamp | null;
  description: string;
  dimension_code: string | null;
  entity_type: string | null;
  id: Generated<string>;
  is_comparable: Generated<boolean>;
  is_filterable: Generated<boolean>;
  key: string;
  max_length: number | null;
  max_numeric: Numeric | null;
  min_length: number | null;
  min_numeric: Numeric | null;
  name: string;
  numeric_scale: number | null;
  required_designation_kind: Generated<string | null>;
  /**
   * Attributes are deprecated and superseded, never deleted: values already recorded against them remain meaningful.
   */
  superseded_by_key: string | null;
  updated_at: Generated<Timestamp>;
  /**
   * NOMINAL_SIZE and PRESSURE_CLASS are deliberately distinct from ENUM and from QUANTITY. Making them their own value types is what makes it structurally impossible for Class 150 to be stored as, or compared against, 150 PSI (ADR-0016).
   */
  value_type: string;
  vocabulary_key: string | null;
}

export interface PimAttributeValue {
  attribute_key: string;
  cardinality: string;
  confidence: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  /**
   * Exactly what the source said, before parsing or normalization. Never overwritten.
   */
  entered_raw: string | null;
  id: Generated<string>;
  ingested_at: Generated<Timestamp>;
  is_selected: Generated<boolean>;
  metadata_version_id: string | null;
  ordinal: Generated<number>;
  owner_key: Generated<string | null>;
  owner_level: Generated<string | null>;
  product_family_id: string | null;
  product_id: string | null;
  product_line_id: string | null;
  selected_at: Timestamp | null;
  selected_reason: string | null;
  source_field: string | null;
  source_record_id: string | null;
  source_system_code: string;
  source_updated_at: Timestamp | null;
  valid_from: Generated<Timestamp>;
  valid_to: Timestamp | null;
  validity: Generated<string | null>;
  value_boolean: boolean | null;
  value_date: Timestamp | null;
  value_entity_id: string | null;
  value_entity_type: string | null;
  value_numeric: Numeric | null;
  value_qty_base: Numeric | null;
  value_qty_dimension: string | null;
  value_qty_max_base: Numeric | null;
  value_qty_max_original: Numeric | null;
  /**
   * The value as entered, in the unit it was entered in. Comparison and filtering use value_qty_base; display defaults to this.
   */
  value_qty_original: Numeric | null;
  value_qty_original_unit: string | null;
  value_term_id: string | null;
  value_text: string | null;
  /**
   * Denormalized from pim.attribute by a cascading composite foreign key, so the CHECK constraints above can enforce type coherence. Changing an attribute value type cascades here, which is why the metadata loader refuses that change while values exist (ADR-0017).
   */
  value_type: string;
  value_vocabulary_key: string | null;
  variant_id: string | null;
  verification_status: Generated<string>;
  verified_at: Timestamp | null;
  verified_by: string | null;
}

export interface PimBrand {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_active: Generated<boolean>;
  key: string;
  name: string;
  owner_organization_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PimCertificationBody {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  name: string;
  website: string | null;
}

export interface PimChannel {
  code: string;
  created_at: Generated<Timestamp>;
  description: string;
  name: string;
  operating_company: string | null;
}

export interface PimIdentifierNamespace {
  code: string;
  created_at: Generated<Timestamp>;
  description: string;
  is_global_unique: Generated<boolean>;
  issuer: string | null;
  name: string;
  value_pattern: string | null;
}

export interface PimMetadataVersion {
  applied_at: Generated<Timestamp>;
  applied_by: string;
  content_hash: string;
  file_count: number;
  id: Generated<string>;
  note: string | null;
  summary: Json;
}

export interface PimProduct {
  brand_id: string;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  deletion_reason: string | null;
  description: string | null;
  id: Generated<string>;
  key: string;
  lifecycle_from: Generated<Timestamp>;
  /**
   * Manufacturer lifecycle. FSW commercial stocking status is a separate concept and lives with channel data, because the two genuinely differ (spec §42).
   */
  lifecycle_status: Generated<string>;
  model_series: string | null;
  name: string;
  product_family_id: string | null;
  product_type_key: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface PimProductCertification {
  certificate_id: string | null;
  certification_term_id: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  expires_on: Timestamp | null;
  id: Generated<string>;
  issued_on: Timestamp | null;
  issuing_body_code: string | null;
  product_id: string | null;
  /**
   * What the certificate covers. Recorded because "the product is 3-A certified" is usually shorthand for "these configurations are".
   */
  scope: string | null;
  source_system_code: string;
  standard_revision: string | null;
  subject_key: Generated<string | null>;
  variant_id: string | null;
  verification_status: Generated<string>;
  verified_at: Timestamp | null;
  verified_by: string | null;
  vocabulary_key: Generated<string>;
}

export interface PimProductFamily {
  created_at: Generated<Timestamp>;
  deprecated_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  key: string;
  name: string;
  product_line_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PimProductIdentifier {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * Carried from the namespace by a cascading composite foreign key so the partial unique index below can be conditioned on it. Never set by hand.
   */
  is_global_unique: boolean;
  namespace_code: string;
  normalized_value: Generated<string | null>;
  product_id: string | null;
  source_system_code: string;
  valid_from: Timestamp | null;
  valid_to: Timestamp | null;
  validation_status: Generated<string>;
  value: string;
  variant_id: string | null;
}

export interface PimProductLine {
  brand_id: string;
  created_at: Generated<Timestamp>;
  deprecated_at: Timestamp | null;
  description: string | null;
  id: Generated<string>;
  key: string;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface PimProductRelationship {
  /**
   * How sure the assertion is. Orthogonal to verification_status: an unverified claim can be confident, and a verified one can be narrow in scope.
   */
  confidence: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  evidence: string | null;
  from_key: Generated<string | null>;
  from_level: Generated<string | null>;
  from_product_id: string | null;
  from_variant_id: string | null;
  id: Generated<string>;
  notes: string | null;
  relationship_type: string;
  source_system_code: string;
  to_key: Generated<string | null>;
  to_level: Generated<string | null>;
  to_product_id: string | null;
  to_variant_id: string | null;
  valid_from: Generated<Timestamp>;
  valid_to: Timestamp | null;
  validity: Generated<string | null>;
  verification_status: Generated<string>;
  verified_at: Timestamp | null;
  verified_by: string | null;
}

export interface PimProductType {
  created_at: Generated<Timestamp>;
  deprecated_at: Timestamp | null;
  description: string;
  etim_class: string | null;
  etim_release: string | null;
  id: Generated<string>;
  key: string;
  name: string;
  parent_key: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PimProductTypeAttribute {
  attribute_key: string;
  /**
   * Applicability predicate in the FSW rule DSL. If actuation is electric, voltage becomes applicable; if pneumatic, supply pressure does. Data, not code.
   */
  condition: Json | null;
  condition_note: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  level: Generated<string>;
  product_type_key: string;
  requirement: Generated<string>;
  sort_order: Generated<number>;
}

export interface PimPublishableVariant {
  channel_code: string | null;
  completeness: Numeric | null;
  evaluated_at: Timestamp | null;
  manufacturer_part_number: string | null;
  product_id: string | null;
  variant_id: string | null;
  warning_count: number | null;
}

export interface PimQualityRule {
  applies_when: Json | null;
  channel_code: string | null;
  created_at: Generated<Timestamp>;
  description: string;
  is_active: Generated<boolean>;
  /**
   * True for rules the evaluator implements directly. The metadata loader leaves them alone: they are not absent from configuration, they were never in it.
   */
  is_system: Generated<boolean>;
  key: string;
  name: string;
  parameters: Generated<Json>;
  product_type_key: string | null;
  rule_kind: string;
  severity: string;
  updated_at: Generated<Timestamp>;
}

export interface PimQuantityDimension {
  code: string;
  description: string;
  name: string;
}

export interface PimRelationshipType {
  code: string;
  created_at: Generated<Timestamp>;
  description: string;
  implies_interchangeable: Generated<boolean>;
  is_directional: Generated<boolean>;
  is_symmetric: Generated<boolean>;
  must_be_acyclic: Generated<boolean>;
  name: string;
  requires_verification: Generated<boolean>;
  sort_order: Generated<number>;
}

export interface PimUnit {
  code: string;
  dimension_code: string;
  /**
   * Exact where the definition is exact: 1 [in_i] = 25.4 mm by definition.
   */
  factor_to_base: Numeric;
  is_base: Generated<boolean>;
  name: string;
  offset_to_base: Generated<Numeric>;
  sort_order: Generated<number>;
  symbol: string;
}

export interface PimUnitAlias {
  alias: string;
  id: Generated<string>;
  /**
   * Uppercased, with punctuation other than / . - removed. Those three are preserved because they carry meaning in engineering designations: 1/2 must not normalize to the same key as 12.
   */
  normalized_alias: Generated<string | null>;
  unit_code: string;
}

export interface PimVariant {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  deletion_reason: string | null;
  description: string | null;
  id: Generated<string>;
  lifecycle_from: Generated<Timestamp>;
  lifecycle_status: Generated<string>;
  manufacturer_part_number: string | null;
  name: string | null;
  product_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface PimVariantFacet {
  attribute_key: string;
  attribute_value_id: string;
  bool_value: boolean | null;
  entity_id: string | null;
  num_max: Numeric | null;
  num_min: Numeric | null;
  /**
   * Normalized base value for quantities -- pascals, kelvin, metres -- not the value as entered. This is what makes a PSI range query match a value entered in bar.
   */
  num_value: Numeric | null;
  ordinal: Generated<number>;
  source_level: string;
  term_id: string | null;
  text_value: string | null;
  value_kind: string;
  variant_id: string;
}

export interface PimVariantQuality {
  blocking_count: Generated<number>;
  channel_code: string;
  completeness: Generated<Numeric>;
  evaluated_at: Generated<Timestamp>;
  is_publishable: boolean;
  variant_id: string;
  warning_count: Generated<number>;
}

export interface PimVariantQualityFinding {
  attribute_key: string | null;
  channel_code: string;
  evaluated_at: Generated<Timestamp>;
  id: Generated<string>;
  message: string;
  rule_key: string;
  severity: string;
  variant_id: string;
}

export interface PimVocabulary {
  created_at: Generated<Timestamp>;
  description: string;
  designation_kind: string | null;
  is_designation: Generated<boolean>;
  key: string;
  name: string;
}

export interface PimVocabularyTerm {
  code: string;
  created_at: Generated<Timestamp>;
  deprecated_at: Timestamp | null;
  description: string | null;
  /**
   * The designation itself: 1, DN25, 150, PN16. For a pressure class the numeral is part of the designation and is NEVER a pressure value.
   */
  designation: string | null;
  id: Generated<string>;
  label: string;
  parent_id: string | null;
  reference_standard: string | null;
  size_system: string | null;
  /**
   * Display and comparison ordering only. Not a measurement and not convertible.
   */
  sort_ordinal: Numeric | null;
  vocabulary_key: string;
}

export interface PimVocabularyTermAlias {
  alias: string;
  asserts_equivalence: Generated<boolean>;
  confidence: Generated<Numeric>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  /**
   * See pim.unit_alias.normalized_alias.
   */
  normalized_alias: Generated<string | null>;
  note: string | null;
  source_system_code: string | null;
  term_id: string;
  vocabulary_key: string;
}

export interface DB {
  "audit.change_log": AuditChangeLog;
  "events.consumer_cursor": EventsConsumerCursor;
  "events.consumer_inbox": EventsConsumerInbox;
  "events.domain_event": EventsDomainEvent;
  "events.event_delivery": EventsEventDelivery;
  "events.event_type_version": EventsEventTypeVersion;
  "events.subscription": EventsSubscription;
  "kernel.idempotency_key": KernelIdempotencyKey;
  "kernel.operating_company": KernelOperatingCompany;
  "kernel.schema_migration": KernelSchemaMigration;
  "kernel.source_system": KernelSourceSystem;
  "pim.attribute": PimAttribute;
  "pim.attribute_value": PimAttributeValue;
  "pim.brand": PimBrand;
  "pim.certification_body": PimCertificationBody;
  "pim.channel": PimChannel;
  "pim.identifier_namespace": PimIdentifierNamespace;
  "pim.metadata_version": PimMetadataVersion;
  "pim.product": PimProduct;
  "pim.product_certification": PimProductCertification;
  "pim.product_family": PimProductFamily;
  "pim.product_identifier": PimProductIdentifier;
  "pim.product_line": PimProductLine;
  "pim.product_relationship": PimProductRelationship;
  "pim.product_type": PimProductType;
  "pim.product_type_attribute": PimProductTypeAttribute;
  "pim.publishable_variant": PimPublishableVariant;
  "pim.quality_rule": PimQualityRule;
  "pim.quantity_dimension": PimQuantityDimension;
  "pim.relationship_type": PimRelationshipType;
  "pim.unit": PimUnit;
  "pim.unit_alias": PimUnitAlias;
  "pim.variant": PimVariant;
  "pim.variant_facet": PimVariantFacet;
  "pim.variant_quality": PimVariantQuality;
  "pim.variant_quality_finding": PimVariantQualityFinding;
  "pim.vocabulary": PimVocabulary;
  "pim.vocabulary_term": PimVocabularyTerm;
  "pim.vocabulary_term_alias": PimVocabularyTermAlias;
}
