/**
 * FSW WorkFit — Business & World Awareness / Memory bank.
 *
 * All exercises, stimuli, questions, choices, and explanations in this file
 * are ORIGINAL FSW Group content authored for this assessment. Nothing here
 * is copied or adapted from any third-party assessment instrument.
 *
 * Part A (exercises): timed study passages with delayed recall questions.
 * Part B (items): durable business/world-awareness questions. Dated
 * current-events items are intentionally excluded; admins add those through
 * a separate workflow.
 */
import type { MemoryBank } from "../types";

export const awarenessMemoryBank: MemoryBank = {
  exercises: [
    {
      key: "mem_vendor_delivery",
      title: "Delivery Notice",
      stimulus:
        "Delivery notice from Calder Supply: Purchase order 88214 will arrive on Thursday between 9:00 and 11:00 a.m. The shipment contains 14 pallets of packaging film and 6 cartons of label stock. The driver must use Dock 4, because Dock 2 is closed for resurfacing. The receiving contact is Marta Villanueva, extension 2280. Any shortage must be noted on the delivery receipt before the driver leaves and reported to Calder's dispatch office within 48 hours. Keep a signed copy of the receipt in the front-office file.",
      studySeconds: 60,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "According to the delivery notice, which dock should the driver use?",
          choices: ["Dock 2", "Dock 3", "Dock 4", "Dock 5"],
          correctIndex: 2,
          explanation: "The notice directs the driver to Dock 4 because Dock 2 is closed for resurfacing.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "How many pallets of packaging film are in the shipment?",
          choices: ["12 pallets", "14 pallets", "16 pallets", "6 pallets"],
          correctIndex: 1,
          explanation: "The shipment contains 14 pallets of packaging film; the 6 refers to cartons of label stock.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 3,
          prompt: "What is the purchase order number on the delivery notice?",
          choices: ["88124", "88241", "82814", "88214"],
          correctIndex: 3,
          explanation: "The purchase order number is 88214; the distractors transpose its digits.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Within how many hours must a shortage be reported to Calder's dispatch office?",
          choices: ["48 hours", "24 hours", "36 hours", "72 hours"],
          correctIndex: 0,
          explanation: "Shortages must be reported to dispatch within 48 hours.",
        },
      ],
    },
    {
      key: "mem_price_change",
      title: "Price Change Memo",
      stimulus:
        "Pricing memo: Effective the first Monday of next quarter, the list price of ProSeal 200 adhesive rises from $18.40 to $19.75 per case. The ProSeal 100 price remains unchanged. Distributors who place an order of 50 cases or more may keep the old price for one final order. Direct all questions to Dana Whitfield in the pricing office, room 310. Updated price sheets will be posted on the internal portal two weeks before the change takes effect, and sales staff should confirm quotes issued during the transition.",
      studySeconds: 60,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "What will the new list price of ProSeal 200 be per case?",
          choices: ["$18.40", "$19.75", "$19.45", "$17.95"],
          correctIndex: 1,
          explanation: "The price rises from $18.40 to $19.75 per case.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Who should receive questions about the price change?",
          choices: ["Dana Whitfield", "Dana Winfield", "Donna Whitfield", "Dana Whitley"],
          correctIndex: 0,
          explanation: "Questions go to Dana Whitfield in the pricing office; the distractors are near-miss names.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "What minimum order size lets a distributor keep the old price for one final order?",
          choices: ["25 cases", "40 cases", "50 cases", "100 cases"],
          correctIndex: 2,
          explanation: "Orders of 50 cases or more qualify for one final order at the old price.",
        },
      ],
    },
    {
      key: "mem_meeting_recap",
      title: "Operations Meeting Recap",
      stimulus:
        "Recap of Tuesday's operations meeting: The team agreed to move the weekly cycle count from Friday afternoon to Wednesday morning, starting next month. Priya Raman will draft the new count schedule by the 20th. The forklift battery replacement was approved at a cost of $3,150 and will be installed during second shift. Two temporary packers will be hired for the busy season, with interviews handled by Luis Ortega. The next meeting is set for the first Tuesday of next month in Conference Room B.",
      studySeconds: 65,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "When will the weekly cycle count take place under the new schedule?",
          choices: ["Friday afternoon", "Monday morning", "Thursday morning", "Wednesday morning"],
          correctIndex: 3,
          explanation: "The count moves from Friday afternoon to Wednesday morning.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "What was the approved cost of the forklift battery replacement?",
          choices: ["$3,050", "$3,510", "$3,150", "$1,350"],
          correctIndex: 2,
          explanation: "The battery replacement was approved at $3,150.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Who will handle interviews for the temporary packers?",
          choices: ["Luis Ortega", "Priya Raman", "Luis Ortiz", "Lucia Ortega"],
          correctIndex: 0,
          explanation: "Luis Ortega handles the interviews; Priya Raman is drafting the count schedule.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "Where will the next operations meeting be held?",
          choices: ["Conference Room A", "Conference Room B", "The break room", "The training center"],
          correctIndex: 1,
          explanation: "The next meeting is in Conference Room B.",
        },
      ],
    },
    {
      key: "mem_product_spec",
      title: "Product Spec Summary",
      stimulus:
        "Spec summary for the TL-450 pallet jack: rated capacity 4,500 pounds, fork length 48 inches, service weight 165 pounds. The lift range runs from 2.9 to 7.5 inches. Replacement wheels use part number W-2205 for the steer wheels and W-2210 for the load rollers. The manufacturer recommends greasing the pivot points every 90 days under normal use. Each unit carries a two-year warranty on the hydraulic pump, and warranty claims must include the unit's serial plate photo.",
      studySeconds: 60,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "What is the rated capacity of the TL-450 pallet jack?",
          choices: ["4,500 pounds", "4,000 pounds", "5,400 pounds", "4,800 pounds"],
          correctIndex: 0,
          explanation: "The TL-450 is rated for 4,500 pounds.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 3,
          prompt: "Which part number is listed for the steer wheels?",
          choices: ["W-2210", "W-2250", "W-5202", "W-2205"],
          correctIndex: 3,
          explanation: "Steer wheels use W-2205; W-2210 is the load-roller part number.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "How often does the manufacturer recommend greasing the pivot points?",
          choices: ["Every 30 days", "Every 90 days", "Every 60 days", "Every 120 days"],
          correctIndex: 1,
          explanation: "Greasing is recommended every 90 days under normal use.",
        },
      ],
    },
    {
      key: "mem_customer_voicemail",
      title: "Customer Voicemail",
      stimulus:
        "Voicemail transcript: \"Hi, this is Gwen Abara from Portside Bakery, phone 555-0142. Our order 7731 arrived today, but we received 9 cases of quart containers instead of the 12 we ordered, and one case was damaged. We need the missing 3 cases plus a replacement case before Saturday, because we cater a large event that weekend. Please call me back before 4 p.m. today, or tomorrow morning after 7. Reference invoice 4462 when you call the warehouse. Thanks.\"",
      studySeconds: 60,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "Which business did the caller say she was from?",
          choices: ["Parkside Bakery", "Portside Cafe", "Portside Bakery", "Bayside Bakery"],
          correctIndex: 2,
          explanation: "The caller, Gwen Abara, is from Portside Bakery.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "How many cases of quart containers did the bakery actually receive?",
          choices: ["9 cases", "12 cases", "3 cases", "10 cases"],
          correctIndex: 0,
          explanation: "The bakery received 9 cases instead of the 12 ordered.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 3,
          prompt: "What invoice number should be referenced when calling the warehouse?",
          choices: ["4426", "4662", "7731", "4462"],
          correctIndex: 3,
          explanation: "The invoice number is 4462; 7731 is the order number.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "By when does the bakery need the missing and replacement cases?",
          choices: ["Before Friday", "Before Saturday", "Before Sunday", "Before Thursday"],
          correctIndex: 1,
          explanation: "The caller asked for the cases before Saturday because of a weekend event.",
        },
      ],
    },
    {
      key: "mem_safety_bulletin",
      title: "Warehouse Safety Bulletin",
      stimulus:
        "Safety bulletin 17: Beginning Monday, all staff entering Aisle 12 through Aisle 18 must wear high-visibility vests, which are stored in the cage by the north entrance. Forklift speed in those aisles is now limited to 3 miles per hour. Spills must be cordoned off immediately and reported to the shift lead within 15 minutes. Refresher training sessions run on the 8th and the 15th at 7:30 a.m. in the break room. Employees who have not completed training by the 22nd will be reassigned until they do.",
      studySeconds: 70,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "What is the new forklift speed limit in the affected aisles?",
          choices: ["5 miles per hour", "3 miles per hour", "10 miles per hour", "2 miles per hour"],
          correctIndex: 1,
          explanation: "Forklift speed in Aisles 12 through 18 is limited to 3 miles per hour.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Where are the high-visibility vests stored?",
          choices: [
            "In the break room",
            "At the south entrance",
            "In the shift lead's office",
            "In the cage by the north entrance",
          ],
          correctIndex: 3,
          explanation: "Vests are stored in the cage by the north entrance.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Within how long must a spill be reported to the shift lead?",
          choices: ["Within 15 minutes", "Within 30 minutes", "Within 1 hour", "By the end of the shift"],
          correctIndex: 0,
          explanation: "Spills must be reported to the shift lead within 15 minutes.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 3,
          prompt: "By what date must employees complete the refresher training to avoid reassignment?",
          choices: ["The 15th", "The 8th", "The 22nd", "The 30th"],
          correctIndex: 2,
          explanation: "Training must be completed by the 22nd; the 8th and 15th are the session dates.",
        },
      ],
    },
    {
      key: "mem_territory_note",
      title: "Territory Assignment Note",
      stimulus:
        "Territory note: Effective next quarter, the eastern accounts split into two routes. Route E-1 covers Harborview, Milldale, and Canton Falls and is assigned to Renee Solis. Route E-2 covers Ashfork and Piner Ridge and is assigned to Tom Ganda. Existing customers keep their current pricing tiers through the transition. Each representative must visit every assigned account at least once in the first 30 days and log each visit in the account system within 24 hours. Route boundaries will be reviewed after six months.",
      studySeconds: 65,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Who is assigned to Route E-1?",
          choices: ["Tom Ganda", "Renee Salas", "Renata Solis", "Renee Solis"],
          correctIndex: 3,
          explanation: "Renee Solis has Route E-1; Tom Ganda has Route E-2.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Which towns are covered by Route E-2?",
          choices: [
            "Harborview and Milldale",
            "Ashfork and Piner Ridge",
            "Canton Falls and Ashfork",
            "Milldale and Piner Ridge",
          ],
          correctIndex: 1,
          explanation: "Route E-2 covers Ashfork and Piner Ridge; the other towns belong to Route E-1.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "How soon after each account visit must the visit be logged?",
          choices: ["Within 48 hours", "Within one week", "Within 24 hours", "Within 30 days"],
          correctIndex: 2,
          explanation: "Visits must be logged within 24 hours; 30 days is the window for the first visits.",
        },
      ],
    },
    {
      key: "mem_travel_itinerary",
      title: "Supplier Visit Itinerary",
      stimulus:
        "Itinerary for the regional supplier visit: Depart Tuesday on flight 218 at 6:55 a.m., arriving at 9:40 a.m. A rental car is reserved under confirmation QK7218. The first meeting is at Brightline Plastics at 1:00 p.m., followed by a plant tour at Kessler Foam on Wednesday at 10 a.m. The hotel is the Garrick Inn on Foster Avenue, two nights, with checkout Thursday by 11 a.m. Submit all receipts to the accounting office within five business days of returning.",
      studySeconds: 60,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "At what time does the Tuesday flight depart?",
          choices: ["6:55 a.m.", "9:40 a.m.", "6:15 a.m.", "7:55 a.m."],
          correctIndex: 0,
          explanation: "Flight 218 departs at 6:55 a.m.; 9:40 a.m. is the arrival time.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 3,
          prompt: "What is the rental car confirmation code?",
          choices: ["QK2718", "KQ7218", "QK7218", "QK7281"],
          correctIndex: 2,
          explanation: "The confirmation code is QK7218; the distractors rearrange its characters.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Which company hosts the plant tour on Wednesday?",
          choices: ["Brightline Plastics", "Garrick Industries", "Kessler Plastics", "Kessler Foam"],
          correctIndex: 3,
          explanation: "The Wednesday plant tour is at Kessler Foam; Brightline Plastics is Tuesday's meeting.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "How soon after returning must receipts be submitted to accounting?",
          choices: [
            "Within ten business days",
            "Within five business days",
            "Within three business days",
            "Within thirty days",
          ],
          correctIndex: 1,
          explanation: "Receipts are due to accounting within five business days of returning.",
        },
      ],
    },
    {
      key: "mem_inventory_alert",
      title: "Inventory Alert",
      stimulus:
        "Inventory alert: Stock of item C-118, the 16-ounce clear deli cup, has fallen to 22 cases against a reorder point of 60. The preferred vendor, Marlin Container, quotes a 10-day lead time; the backup vendor, Apex Packaging, can ship in 4 days at an 8 percent higher cost. Current usage averages 11 cases per week. Purchasing recommends ordering 150 cases from Marlin today and 40 cases from Apex as a bridge. Approval is needed from the operations manager by end of day Friday.",
      studySeconds: 65,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "How many cases of item C-118 are currently in stock?",
          choices: ["60 cases", "11 cases", "22 cases", "40 cases"],
          correctIndex: 2,
          explanation: "Stock has fallen to 22 cases; 60 is the reorder point and 11 is weekly usage.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "Which company is named as the backup vendor?",
          choices: ["Apex Packaging", "Marlin Container", "Apex Container", "Marlin Packaging"],
          correctIndex: 0,
          explanation: "Apex Packaging is the backup vendor; Marlin Container is the preferred vendor.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "How many cases does purchasing recommend ordering from Marlin?",
          choices: ["40 cases", "60 cases", "110 cases", "150 cases"],
          correctIndex: 3,
          explanation: "The recommendation is 150 cases from Marlin, with 40 from Apex as a bridge.",
        },
      ],
    },
    {
      key: "mem_training_schedule",
      title: "Training Notice",
      stimulus:
        "Training notice: New-hire orientation moves to a two-day format next month. Day one covers safety and equipment basics in Room 104, starting at 8:30 a.m. Day two covers order-entry software, led by Marcus Bell, in the computer lab. Class size is capped at 12. Supervisors must enroll new hires at least one week before a session through the HR portal. Attendance is recorded, and anyone who misses a day must rebook within 14 days. Lunch is provided on day one only.",
      studySeconds: 60,
      questions: [
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Where does day one of orientation take place?",
          choices: ["Room 140", "Room 104", "The computer lab", "Room 401"],
          correctIndex: 1,
          explanation: "Day one is in Room 104; the computer lab hosts day two.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 2,
          prompt: "Who leads the day-two software session?",
          choices: ["Martin Bell", "Marcus Ball", "Mark Bellamy", "Marcus Bell"],
          correctIndex: 3,
          explanation: "Marcus Bell leads the order-entry software session on day two.",
        },
        {
          construct: "AWARENESS_MEMORY",
          subtype: "memory_recall",
          difficulty: 1,
          prompt: "What is the maximum class size for an orientation session?",
          choices: ["12", "10", "14", "20"],
          correctIndex: 0,
          explanation: "Class size is capped at 12.",
        },
      ],
    },
  ],
  items: [
    // ------------------------------------------------------------------
    // economic_concepts (16)
    // ------------------------------------------------------------------
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 1,
      prompt: "In practical terms, what does inflation mean for a business that buys supplies?",
      choices: [
        "The same supplies tend to cost more money over time",
        "Suppliers are required to lower their prices each year",
        "The business must switch to new suppliers",
        "The quantity of supplies available always increases",
      ],
      correctIndex: 0,
      explanation: "Inflation is a general rise in prices, so the same goods cost more over time.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 1,
      prompt:
        "When interest rates rise, what generally happens for a business that wants to borrow money for new equipment?",
      choices: [
        "Its existing equipment loses its warranty",
        "The loan is approved automatically",
        "The loan becomes more expensive to repay",
        "The equipment price is frozen by the lender",
      ],
      correctIndex: 2,
      explanation: "Higher interest rates raise the cost of borrowing, making loan repayment more expensive.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 1,
      prompt: "During a recession, which change should a typical retail business most reasonably expect?",
      choices: [
        "Customers spending more freely than usual",
        "Customers cutting back on their spending",
        "Suppliers giving away goods at no charge",
        "Rents automatically dropping to zero",
      ],
      correctIndex: 1,
      explanation: "A recession is a broad decline in economic activity, so consumers typically spend less.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 2,
      prompt:
        "A company pays an overseas supplier in that supplier's currency. If the company's home currency weakens, what happens to the cost of those purchases?",
      choices: [
        "It stays exactly the same",
        "It drops to zero",
        "It goes down in home-currency terms",
        "It goes up in home-currency terms",
      ],
      correctIndex: 3,
      explanation: "A weaker home currency buys less foreign currency, so the same purchases cost more at home.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 1,
      prompt: "What is a tariff, in practical business terms?",
      choices: [
        "A discount for buying in bulk",
        "A fee charged by a bank for a loan",
        "A subsidy paid to exporters",
        "A tax charged on goods brought in from another country",
      ],
      correctIndex: 3,
      explanation: "A tariff is a tax on imports, which raises the cost of goods brought in from abroad.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 1,
      prompt: "If demand for a product stays steady but the supply becomes scarce, what typically happens to its price?",
      choices: [
        "It tends to rise",
        "It tends to fall",
        "It is unaffected by supply",
        "It must be cut in half",
      ],
      correctIndex: 0,
      explanation: "When supply falls while demand holds steady, prices tend to rise.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 2,
      prompt: "When interest rates fall, what generally happens to the money a business earns on its savings account?",
      choices: [
        "It grows faster than before",
        "It is converted into shares",
        "It earns less interest than before",
        "It is automatically taxed at a lower rate",
      ],
      correctIndex: 2,
      explanation: "Lower rates mean deposits earn less interest than they did before.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 3,
      prompt:
        "A contractor signs a two-year agreement to deliver services at a fixed price. If inflation runs higher than expected, what happens to the contractor's position?",
      choices: [
        "The contractor's costs are locked in along with the price",
        "The contractor's real profit on the contract shrinks as costs rise",
        "The customer is required to renegotiate the price",
        "The contractor's profit automatically rises with inflation",
      ],
      correctIndex: 1,
      explanation: "The revenue is fixed while the contractor's own costs rise, squeezing the real profit.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 2,
      prompt: "When unemployment in a region is high, what does that usually mean for a business trying to hire?",
      choices: [
        "There are fewer applicants for each opening",
        "There are usually more applicants for each opening",
        "Wages are legally required to increase",
        "Hiring is prohibited until unemployment falls",
      ],
      correctIndex: 1,
      explanation: "High unemployment means more people are seeking work, so openings typically draw more applicants.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 2,
      prompt: "What does 'purchasing power' refer to?",
      choices: [
        "The legal authority to sign purchase contracts",
        "The size of a company's purchasing department",
        "A store's ability to open new locations",
        "How much goods and services a given amount of money can buy",
      ],
      correctIndex: 3,
      explanation: "Purchasing power is the amount of goods and services money can buy; inflation erodes it.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 3,
      prompt:
        "A country's currency strengthens significantly. What is the likely effect on a manufacturer in that country that sells mostly to foreign buyers?",
      choices: [
        "Its products become more expensive for those buyers",
        "Its products become cheaper for those buyers",
        "Its foreign sales are unaffected by the currency",
        "It no longer has to pay for shipping",
      ],
      correctIndex: 0,
      explanation: "A stronger currency makes exports cost more in foreign buyers' money, which can hurt sales abroad.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 2,
      prompt: "What does compound interest mean for money left in an account?",
      choices: [
        "Interest is paid only once, at the end",
        "Interest is paid only when money is withdrawn",
        "Interest is earned on both the original amount and the interest already added",
        "Interest is subtracted from the original amount",
      ],
      correctIndex: 2,
      explanation: "Compounding means previously earned interest itself earns interest, so balances grow faster over time.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 1,
      prompt: "Fuel prices rise sharply and stay high. Which business is most directly affected?",
      choices: [
        "A firm that sells services entirely online with no shipping",
        "A landlord collecting fixed monthly rents",
        "A delivery company operating a large truck fleet",
        "A bookkeeper who works from home",
      ],
      correctIndex: 2,
      explanation: "Fuel is a major operating cost for a truck fleet, so a delivery company is hit most directly.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 2,
      prompt: "A business has a line of credit with a variable interest rate. If market rates rise, what happens?",
      choices: [
        "The amount borrowed is automatically reduced",
        "The interest cost on the borrowed balance goes up",
        "The lender must forgive part of the loan",
        "The rate stays fixed for the life of the line",
      ],
      correctIndex: 1,
      explanation: "A variable rate moves with the market, so rising rates increase the interest expense.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 3,
      prompt: "Why can raising interest rates help slow inflation?",
      choices: [
        "Higher rates force stores to close",
        "Higher rates increase the amount of money in circulation",
        "Higher rates immediately make imported goods cheaper",
        "Borrowing and spending tend to slow, easing upward pressure on prices",
      ],
      correctIndex: 3,
      explanation: "Costlier borrowing dampens spending and demand, which relieves pressure on prices.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "economic_concepts",
      difficulty: 3,
      prompt:
        "Prices in an economy begin falling steadily and are expected to keep falling. Why can this hurt sellers of big-ticket goods?",
      choices: [
        "Customers may delay purchases, expecting lower prices later",
        "Falling prices always increase profit margins",
        "Customers are required to buy sooner",
        "Sellers are no longer allowed to advertise",
      ],
      correctIndex: 0,
      explanation: "When buyers expect prices to keep dropping, they postpone large purchases, weakening sales.",
    },
    // ------------------------------------------------------------------
    // business_awareness (16)
    // ------------------------------------------------------------------
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 1,
      prompt: "What does a distributor mainly do?",
      choices: [
        "Buys products from manufacturers and resells them to stores and businesses",
        "Designs new products for manufacturers",
        "Lends money to retailers",
        "Inspects factories for safety compliance",
      ],
      correctIndex: 0,
      explanation: "A distributor is a middle link that buys from producers and resells to retailers or other businesses.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 2,
      prompt:
        "A key component a factory needs is stuck at a closed port. What does this supply-chain disruption most directly threaten?",
      choices: [
        "The factory's marketing plan",
        "The factory's brand name",
        "The factory's ability to keep production running",
        "The factory's tax rate",
      ],
      correctIndex: 2,
      explanation: "Without needed inputs, production can stall, so the disruption directly threatens output.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 2,
      prompt: "What is the main difference between an accounts-payable clerk and a buyer?",
      choices: [
        "The clerk sells goods, while the buyer audits them",
        "The clerk processes and pays supplier invoices, while the buyer selects and orders goods",
        "The clerk manages staff, while the buyer manages payroll",
        "There is no real difference between the two roles",
      ],
      correctIndex: 1,
      explanation: "Accounts payable handles paying what the company owes; buyers decide what to purchase and place orders.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 1,
      prompt: "Why do businesses track profit margin?",
      choices: [
        "To count how many employees they have",
        "To measure their warehouse square footage",
        "To set the office holiday schedule",
        "To know how much of each sale is left after covering costs",
      ],
      correctIndex: 3,
      explanation: "Margin shows the portion of each sale remaining after costs, a core measure of business health.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 2,
      prompt: "What does the payment term 'net 30' on an invoice mean?",
      choices: [
        "A 30 percent discount applies to the invoice",
        "Payment is made in 30 equal installments",
        "The order contains 30 items",
        "The full amount is due within 30 days",
      ],
      correctIndex: 3,
      explanation: "Net 30 means the buyer must pay the full invoice amount within 30 days.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 1,
      prompt: "What is the difference between wholesale and retail?",
      choices: [
        "Wholesale sells in bulk to businesses; retail sells to individual consumers",
        "Wholesale is always online; retail is always in physical stores",
        "Wholesale sells services; retail sells goods",
        "Wholesale is nonprofit; retail is for profit",
      ],
      correctIndex: 0,
      explanation: "Wholesalers sell larger quantities to businesses, while retailers sell to end consumers.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 2,
      prompt: "Why can holding too much inventory be a problem, even if the goods eventually sell?",
      choices: [
        "Inventory always spoils within a month",
        "Suppliers refuse to sell more to the business",
        "It ties up cash and storage space in unsold goods",
        "It lowers the quality of the goods",
      ],
      correctIndex: 2,
      explanation: "Money spent on stock sitting in storage is unavailable for other needs, and storage itself costs money.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 1,
      prompt: "A customer's item is on backorder. What does that mean?",
      choices: [
        "The item has been discontinued permanently",
        "The item is out of stock now and will ship when new stock arrives",
        "The item was returned by another customer",
        "The item ships only to business addresses",
      ],
      correctIndex: 1,
      explanation: "A backorder is an accepted order for an out-of-stock item, to be filled when stock is replenished.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 2,
      prompt: "What does 'overhead' refer to in a business?",
      choices: [
        "The profit made on each unit sold",
        "Ongoing costs like rent and utilities that are not tied to a specific product",
        "Money owed to the business by its customers",
        "The value of the company's inventory",
      ],
      correctIndex: 1,
      explanation: "Overhead covers general operating costs, such as rent and utilities, not tied to producing one item.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 1,
      prompt: "What is a purchase order?",
      choices: [
        "A record of goods a customer returned",
        "A bill requesting payment from a customer",
        "A summary of a company's yearly profits",
        "A document a buyer sends a supplier specifying what it wants to buy",
      ],
      correctIndex: 3,
      explanation: "A purchase order tells a supplier what the buyer wants, in what quantity, and at what agreed price.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 2,
      prompt: "Why do businesses forecast their sales for the months ahead?",
      choices: [
        "So they can plan staffing, inventory, and spending to match expected demand",
        "Because forecasts are legally required for all companies",
        "To guarantee that the forecasted sales will happen",
        "To decide which customers to refuse service",
      ],
      correctIndex: 0,
      explanation: "Forecasts guide decisions about staffing, purchasing, and budgets so resources match expected demand.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 2,
      prompt: "What does 'lead time' mean when ordering from a supplier?",
      choices: [
        "The weight of the shipment",
        "The discount given for early payment",
        "The time between placing the order and receiving the goods",
        "The distance to the supplier's warehouse",
      ],
      correctIndex: 2,
      explanation: "Lead time is how long delivery takes after an order is placed, which drives reorder planning.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 3,
      prompt: "A company shows a profit on paper but struggles to pay this month's bills. What best explains this?",
      choices: [
        "Profit reported on paper is always false",
        "Profitable companies cannot have unpaid bills",
        "Cash can lag profit when customers have not yet paid their invoices",
        "The company must have no customers at all",
      ],
      correctIndex: 2,
      explanation: "Profit and cash flow differ: sales may be booked as profit before the customer cash actually arrives.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 1,
      prompt: "What is the main purpose of quality control in a production operation?",
      choices: [
        "To advertise the finished product",
        "To catch defects before products reach customers",
        "To speed up the hiring process",
        "To reduce the price of raw materials",
      ],
      correctIndex: 1,
      explanation: "Quality control checks output against standards so defective goods are caught before shipping.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 3,
      prompt: "Why do many businesses invest in keeping existing customers rather than only chasing new ones?",
      choices: [
        "Existing customers are legally bound to keep buying",
        "New customers always spend more than existing ones",
        "Existing customers never complain about service",
        "Winning a new customer usually costs more than retaining a current one",
      ],
      correctIndex: 3,
      explanation: "Acquiring new customers typically requires more marketing and sales effort than keeping current ones.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "business_awareness",
      difficulty: 2,
      prompt: "What does a markup refer to in pricing?",
      choices: [
        "The amount added to an item's cost to set its selling price",
        "The tax charged at the register",
        "The fee charged for late payment",
        "The cost of shipping an item",
      ],
      correctIndex: 0,
      explanation: "Markup is the difference added on top of cost to arrive at the selling price.",
    },
    // ------------------------------------------------------------------
    // info_interpretation (16)
    // ------------------------------------------------------------------
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 2,
      prompt:
        "A notice reads: 'Orders received by 2 p.m. ship the same day; orders received later ship the next business day.' An order arrives Friday at 3:15 p.m. When will it ship?",
      choices: [
        "On the next business day",
        "The same Friday",
        "It will not ship at all",
        "Within one hour of arrival",
      ],
      correctIndex: 0,
      explanation: "The order arrived after 2 p.m., so under the stated rule it ships the next business day.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 1,
      prompt:
        "A policy states: 'Returns are accepted within 30 days of purchase with a receipt.' A customer has a receipt for an item bought 45 days ago. What follows?",
      choices: [
        "The return must be accepted because there is a receipt",
        "The customer may return it within 30 more days",
        "The return falls outside the policy window",
        "The receipt is invalid",
      ],
      correctIndex: 2,
      explanation: "Both conditions must be met; at 45 days the purchase is outside the 30-day window.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 3,
      prompt:
        "Vendor A sells a part for $12 each with a 100-unit minimum order. Vendor B sells the same part for $13 each with no minimum. A shop needs exactly 60 units. Which order costs less in total?",
      choices: [
        "Vendor A, at a total of $720",
        "Vendor B, at a total of $780",
        "Vendor A, at a total of $1,200",
        "Both orders cost the same",
      ],
      correctIndex: 1,
      explanation: "Vendor A's minimum forces buying 100 units for $1,200; Vendor B fills 60 units for $780.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 1,
      prompt:
        "A memo says: 'The employee lot is closed Tuesday for repaving; please use the Elm Street garage that day.' What should employees do on Tuesday?",
      choices: [
        "Park in the employee lot as usual",
        "Work from home",
        "Avoid driving on Elm Street",
        "Park in the Elm Street garage",
      ],
      correctIndex: 3,
      explanation: "The memo directs employees to use the Elm Street garage while the lot is closed on Tuesday.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 2,
      prompt:
        "A supplier raised the cost of an ingredient by 5 percent, and the bakery kept its own selling prices unchanged. What follows about the bakery's margin on items using that ingredient?",
      choices: [
        "The margin increased",
        "The margin stayed the same",
        "The margin doubled",
        "The margin decreased",
      ],
      correctIndex: 3,
      explanation: "With costs up and selling prices flat, the difference between them — the margin — shrinks.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 3,
      prompt:
        "A report notes that customer complaints fell during the same quarter the company introduced new packaging and also switched delivery carriers. What can be concluded?",
      choices: [
        "The data alone cannot show which change, if either, caused the drop",
        "The new packaging caused the drop in complaints",
        "The new delivery carrier caused the drop in complaints",
        "Complaints are guaranteed to keep falling next quarter",
      ],
      correctIndex: 0,
      explanation: "Two changes happened at once, so the report cannot attribute the improvement to either one.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 2,
      prompt:
        "Company policy requires two signatures on any check over $1,000. A clerk is handed a $1,200 check bearing one signature. What follows?",
      choices: [
        "The check satisfies the policy because it is under $2,000",
        "Only checks over $5,000 require review",
        "The check does not yet meet the policy's requirements",
        "The policy does not apply to clerks",
      ],
      correctIndex: 2,
      explanation: "The check exceeds $1,000, so it needs a second signature before it complies with policy.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 2,
      prompt:
        "A production line makes 200 units per hour. The line was stopped for 4 hours on Monday. About how much production was lost?",
      choices: [
        "About 200 units",
        "About 800 units",
        "About 50 units",
        "About 4,000 units",
      ],
      correctIndex: 1,
      explanation: "Four hours at 200 units per hour is roughly 800 units of lost production.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 3,
      prompt:
        "A survey of customers who canceled their service found that 70 percent of them cited slow delivery. Which statement follows?",
      choices: [
        "70 percent of all customers are unhappy with delivery",
        "Slow delivery was the most commonly cited reason among the surveyed cancelers",
        "Fixing delivery speed will win back every canceled customer",
        "Only 30 percent of cancelers had a genuine reason to leave",
      ],
      correctIndex: 1,
      explanation: "The finding applies only to surveyed cancelers; it says nothing about all customers or future behavior.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 3,
      prompt: "Branch A's quarterly profit rose even though its revenue fell. Which statement must be true?",
      choices: [
        "The branch sold more units than before",
        "The branch raised its prices",
        "The branch hired more staff",
        "The branch's costs fell by more than its revenue did",
      ],
      correctIndex: 3,
      explanation: "Profit is revenue minus costs; with revenue down, only a larger drop in costs can raise profit.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 2,
      prompt:
        "Inventory is counted every three months. The last count was completed on March 3. Around when is the next count due?",
      choices: [
        "Around early June",
        "Around early April",
        "Around early September",
        "Around the end of March",
      ],
      correctIndex: 0,
      explanation: "Three months after March 3 falls in early June.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 2,
      prompt:
        "Each trainer can supervise at most 6 trainees. A session has 20 trainees enrolled. What is the minimum number of trainers needed?",
      choices: ["3 trainers", "6 trainers", "4 trainers", "2 trainers"],
      correctIndex: 2,
      explanation: "Three trainers cover only 18 trainees; a fourth is needed for the remaining 2.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 3,
      prompt:
        "The East warehouse fills 60 percent of orders with a 2 percent error rate; the West warehouse fills 40 percent with a 1 percent error rate. Where do most order errors come from?",
      choices: [
        "West, because its share of orders is smaller",
        "Both warehouses contribute exactly equally",
        "East, because its larger volume and higher rate produce more errors",
        "Neither warehouse produces any errors",
      ],
      correctIndex: 2,
      explanation: "East contributes 1.2 errors per 100 total orders versus West's 0.4, so most errors come from East.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 1,
      prompt:
        "A promotion states: 'New customers receive 15 percent off their first order only.' A new customer places a second order. What follows?",
      choices: [
        "The discount applies to both orders",
        "The second order is not discounted under this promotion",
        "The second order gets 30 percent off",
        "The customer must return the first order",
      ],
      correctIndex: 1,
      explanation: "The promotion is limited to the first order, so the second order gets no discount from it.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 3,
      prompt:
        "A store's sales were 20 percent higher during the three months it stayed open two extra evening hours. Which conclusion is best supported?",
      choices: [
        "The extra hours caused the entire increase",
        "Evening customers spend more per visit than daytime customers",
        "Extending hours permanently will guarantee continued growth",
        "Sales were higher during that period, but other factors could also have contributed",
      ],
      correctIndex: 3,
      explanation: "The figures show an association only; other factors such as seasonality could explain part of the rise.",
    },
    {
      construct: "AWARENESS_MEMORY",
      subtype: "info_interpretation",
      difficulty: 1,
      prompt: "A sign reads: 'Free delivery on orders of $500 or more.' Dana's order totals $480. What follows?",
      choices: [
        "Dana's order does not qualify for free delivery",
        "Dana's order qualifies because it is close to $500",
        "Delivery is free only for orders under $500",
        "Dana is not allowed to place the order",
      ],
      correctIndex: 0,
      explanation: "The order is below the stated $500 threshold, so it does not qualify for free delivery.",
    },
  ],
};
