/**
 * Vendor name canonicalization for Product Purchase Mix.
 *
 * VENDOR values are trimmed, whitespace-collapsed and compared case-insensitively.
 * The tracker also records the same vendor under several obvious spellings
 * (with/without corporate suffixes, abbreviations). Those are consolidated here so
 * one vendor is not counted twice. Only aliases that the workbook itself makes
 * unambiguous are included. Keys are matched after normalization (lower-case,
 * punctuation removed, repeated spaces collapsed).
 */
export const VENDOR_ALIASES: Record<string, string> = {
  'bonomi north america inc': 'Bonomi',
  'bonomi north america': 'Bonomi',
  bonomi: 'Bonomi',
  'stc valve company': 'STC',
  stc: 'STC',
  'conbraco industries inc': 'Conbraco',
  'conbraco industries': 'Conbraco',
  conbraco: 'Conbraco',
  'watts regulator co': 'Watts',
  watts: 'Watts',
  'gc valves': 'GC Valves',
  'g c valves': 'GC Valves',
  'gc valve': 'GC Valves',
  'gc valves dema': 'GC Valves',
  'titan flow control inc': 'Titan',
  'titan flow control': 'Titan',
  titan: 'Titan',
  'red white valve corp': 'Red-White Valve',
  'red white valve': 'Red-White Valve',
  'red white valves': 'Red-White Valve',
  'red white': 'Red-White Valve',
  rwv: 'Red-White Valve',
  'jomar valve': 'Jomar',
  'jomar valves': 'Jomar',
  jomar: 'Jomar',
  'controlair llc': 'ControlAir',
  controlair: 'ControlAir',
  'j flow controls': 'J Flow Controls',
  'j flow': 'J Flow Controls',
  jflow: 'J Flow Controls',
  'plast o matic': 'Plast-O-Matic',
  'plast o maic': 'Plast-O-Matic',
  'max air technology inc': 'Max-Air',
  'max air technology': 'Max-Air',
  'max air': 'Max-Air',
  maxair: 'Max-Air',
  'triac controls division of a t controls': 'Triac',
  'a t controls inc': 'A-T Controls',
  'a t controls': 'A-T Controls',
  'ives equipment corporation': 'Ives',
  ives: 'Ives',
  'valvetech industrial': 'ValveTech',
  valvetech: 'ValveTech',
  'aquatrol inc': 'Aquatrol',
  aquatrol: 'Aquatrol',
  'main line supply co inc': 'Main Line Supply',
  'main line supply co': 'Main Line Supply',
  'main line': 'Main Line Supply',
  mainline: 'Main Line Supply',
  'louis p canuso inc': 'LP Canuso',
  'lp canuso': 'LP Canuso',
  lpcanuso: 'LP Canuso',
  'lp canuso freight': 'LP Canuso',
  'reotemp instruments': 'Reotemp',
  reotemp: 'Reotemp',
  'chicago valves': 'Chicago Valves',
  'chicago valve': 'Chicago Valves',
  chicago: 'Chicago Valves',
  cvc: 'Chicago Valves',
  'noshok inc': 'Noshok',
  noshok: 'Noshok',
  'matco norca llc': 'Matco-Norca',
  'matco norca': 'Matco-Norca',
  'layden company': 'Layden',
  layden: 'Layden',
  'sanitary solutions group llc': 'Sanitary Solutions Group',
  'sanitary solutions': 'Sanitary Solutions Group',
  sanitary: 'Sanitary Solutions Group',
  'flo tite inc': 'Flo-Tite',
  'flo tite': 'Flo-Tite',
  flotite: 'Flo-Tite',
  'tektrol llc': 'Tek-Trol',
  tektrol: 'Tek-Trol',
  'tek trol': 'Tek-Trol',
  'dft inc': 'DFT',
  dft: 'DFT',
  'praher plastics': 'Praher',
  praher: 'Praher',
  'steriflow valves': 'Steriflow',
  'steriflow a division of richards industrials': 'Steriflow',
  steriflow: 'Steriflow',
  'svf flow controls': 'SVF',
  svf: 'SVF',
  'wiltech inc': 'Wiltech',
  wiltech: 'Wiltech',
  'key international inc': 'Key International',
  'butterfly valves and controls inc': 'Butterfly Valves & Controls',
  'butterfly valves controls': 'Butterfly Valves & Controls',
  'flow control inc': 'Flow Control',
  'flow control': 'Flow Control',
  'co ax': 'Co-Ax',
  coax: 'Co-Ax',
  'watson mcdaniel': 'Watson McDaniel',
  watson: 'Watson McDaniel',
  'wayland industries': 'Wayland Industries',
  wayland: 'Wayland Industries',
  'newmans valve llc': 'Newmans Valve',
  'newmans valve': 'Newmans Valve',
  newmans: 'Newmans Valve',
  'ifm efector inc': 'IFM',
  ifm: 'IFM',
  'asc engineered solutions': 'ASC Engineered Solutions',
  asc: 'ASC Engineered Solutions',
  'cla val': 'Cla-Val',
  'davis valve stovall engineering': 'Davis Valve',
  'davis valve': 'Davis Valve',
  'aiv l p zenith supply company': 'AIV',
  aiv: 'AIV',
};

/**
 * VENDOR cell values that are not vendors at all (status text, placeholders).
 * These never count toward Product Purchase Mix.
 */
export const VENDOR_STOPLIST_PATTERNS: RegExp[] = [
  /^-+$/,
  /^\?+$/,
  /^n\/?a$/i,
  /^none$/i,
  /^tbd$/i,
  /^cancel+ed$/i,
  /^deleted\?*$/i,
  /^credit memo$/i,
  /^return(ed)?$/i,
  /^refund(ed)?$/i,
  /^replacement$/i,
  /^sample\??$/i,
  /\bsample\b/i,
  /^rga#?/i,
  /^ships? to vm$/i,
  /^shipping direct/i,
  /^vm$/i,
  /^vm warehouse$/i,
  /^valveman( inventory| warehouse)?$/i,
  /^valveman warehouse/i,
  /^f\.?\s?s\.?\s?welsford( company)?$/i,
  /^fs welsford$/i,
  /^warehouse$/i,
  /^customer$/i,
  /^po \d+/i,
  /^\d+ ship vm$/i,
];

/**
 * Internal entities that are pass-through sellers rather than the product vendor.
 * When a VENDOR cell reads "Internal > Manufacturer", the manufacturer is used.
 */
export const INTERNAL_PASSTHROUGH_PATTERNS: RegExp[] = [
  /^f\.?\s?s\.?\s?welsford/i,
  /^fs welsford/i,
  /^valveman/i,
  /^vm$/i,
  /^vm warehouse$/i,
];
